name: .NET Core

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        dotnet build "SubstrateCS/SubStrate (NET4).csproj" -c Release