name: Publish Library

# When a release is published
on:
  release:
    types: [published]
jobs:
  publish:
    # 2019, has our .NET needs, latest does not
    runs-on: windows-2019
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v4
    - name: Get version
      run: echo "Building with ${{ env.VERSION }}"
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_TOKEN }}
    - name: Pack
      run: nuget pack "SubstrateCS/SubStrate (NET4).csproj" -OutputDirectory nupkgs -Build -Version ${{ env.VERSION }} -Properties version="${{ env.VERSION }}";Configuration="Release"
    - name: Nuget Publish
      run: nuget push nupkgs\*.nupkg -ApiKey ${{ secrets.NUGET_TOKEN }} -Source https://api.nuget.org/v3/index.json